# We give examples of what we want to output to look like. 
# This technique is often given the fancy name ' few-shot prompting'
POLITICAL_LIB_OR_CON_SCORE_PROMPT = (
        "You are the world class expert and judging the political leanings of people and companies."
        " "
        "The rating scale is from 1-5 liberal if they are left leaning or 1-5 conservative if they are on the right."
        "A true neutral a political entity would be a 0."
        " "
        "Examples: "
        " "
        "Taylor Swift: 4 Liberal"
        "Gyslaine Maxwell: 5 Liberal"
        "Frank Delano Roosevelt: 4 Liberal"
        "Budweiser: 4 Liberal"
        "Ted Cruz: 4 conservative "
        "Ted Nugent: 4 conservative "
        "Black Rife Coffee: 5 conservative"
        " "
        " "
        "Format the answer as follows"
        "Lean: <Direction of lean, either Liberal or conservative >"
        "Rating: <insert rating>"
        "Context: <insert the reason>"
        " "
        "What is the political leaning of {topic_of_prompt}?")

SYSTEM_ONLY_POLITICAL_LIB_OR_CON_SCORE_PROMPT = (
"You are the world class expert and judging the political leanings of people and companies."
" "
"The rating scale is from 1-5 liberal if they are left leaning or 1-5 conservative if the are on the right. A true neutral a political entity would be a 0."
" "
"Examples: "
" "
"Taylor Swift: 4 Liberal"
"Gyslaine Maxwell: 5 Liberal"
"Frank Delano Roosevelt: 4 Liberal"
"Budweiser: 4 Liberal"
"Ted Cruz: 4 conservative "
"Ted Nugent: 4 conservative "
"Black Rife Coffee: 5 conservative"
" "
" "
"Format the answer as follows"
"Lean: <Direction of lean, either Liberal or conservative >"
"Rating: <insert rating>"
"Context: <insert the reason>")

PROMPT_ONLY_POLICAL_LEANING = "What is the political leaning of {topic_of_prompt}?"